function [rawdata, headerinfo] = readoldforcecurve (filename) 

%% OPEN THE FILE
forcefile=fopen(filename);

%% THE FOLLOWING READS THE HEADERINFOS
xposition = textscan (forcefile,'# xPosition: %f',1);
yposition = textscan (forcefile,'# yPosition: %f',1);
index = textscan (forcefile,'# index: %d',1);
approachID = textscan (forcefile,'# approachID: %s',1);
forceSettings = textscan (forcefile,'# forceSettings: %s',1);
zRelativeStart = textscan (forcefile,'# zRelativeStart: %f',1);
zRelativeEnd = textscan (forcefile,'# zRelativeEnd: %f',1);
setpoint = textscan (forcefile,'# setpoint: %f',1);
kLength = textscan (forcefile,'# kLength: %d',1);
zStartPauseOption = textscan (forcefile,'# zStartPauseOption: %s',1);
zEndPauseOption = textscan (forcefile, '# zEndPauseOption: %s',1);
tipsaverPauseOption = textscan (forcefile, '# tipsaverPauseOption: %s',1);
feedbackMode = textscan (forcefile, '# feedbackMode: %s',1);
traceScanTime = textscan (forcefile, '# traceScanTime: %f',1);
retraceScanTime = textscan (forcefile, '# retraceScanTime: %f',1);
pauseBeforeFirst = textscan (forcefile, '# pauseBeforeFirst: %f',1);
pauseAtStart = textscan (forcefile, '# pauseAtStart: %f',1);
pauseAtEnd = textscan (forcefile, '# pauseAtEnd: %f',1);
pauseOnTipsaver = textscan (forcefile, '# pauseOnTipsaver: %f',1);
scanner = textscan (forcefile, '# scanner: %s',1);
date = textscan (forcefile, '# date: %s %s %d %s %s %d',1);
empty = textscan (forcefile, '#',1);
direction = textscan (forcefile, '# direction: %s',1);
columns = textscan (forcefile, '# columns: %s %s %s %s %s',1);
fancyNames = textscan (forcefile, '# fancyNames: %q %q %q %q %q',1);
heightMultiplier = textscan (forcefile, '# heightMultiplier: %f',1);
heightOffset = textscan (forcefile, '# heightOffset: %f',1);
sensitivity = textscan (forcefile, '# sensitivity: %f',1);
springConstant = textscan (forcefile, '# springConstant: %f',1); 
calibrationSlots = textscan (forcefile, '# calibrationSlots: %s %s %s %s %s',1);
units = textscan (forcefile, '# units: %s %s %s %s %s',1);
empty = textscan (forcefile, '#',1);

%% READ DATA (CURRENTLY ONLY TRACE)
rawdata = textscan (forcefile, '%f %f %f %f %f');
headerinfo = {'xposition',xposition;...
    'yposition',yposition;...
    'index',index;...
    'approachID',approachID;...
    'forceSettings',forceSettings;...
    'zRelativeStart',zRelativeStart;...
    'zRelativeEnd',zRelativeEnd;...
    'setpoint',setpoint;...
    'kLength',kLength;...
    'zStartPauseOption',zStartPauseOption;...
    'zEndPauseOption',zEndPauseOption;...
    'tipsaverPauseOption',tipsaverPauseOption;...
    'feedbackmode',feedbackMode;...
    'traceScanTime',traceScanTime;...
    'retraceScanTime',retraceScanTime;...
    'pauseBeforeFirst',pauseBeforeFirst;...
    'pauseAtStart',pauseAtStart;...
    'pauseAtEnd',pauseAtEnd;...
    'pauseOnTipsaver',pauseOnTipsaver;...
    'scanner',scanner;...
    'date',date;...
    'direction',direction;...
    'columns',columns;...
    'fancyNames',fancyNames;...
    'heightMultiplier',heightMultiplier;...
    'heightOffset',heightOffset;...
    'sensitivity',sensitivity;...
    'springConstant',springConstant;...
    'calibrationSlots',calibrationSlots;...
    'units',units;};
%% CLOSE THE FILE
fclose('all');